name: arxiv-reproducibility
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Certify arxiv paper reproducibility
        uses: pbizopoulos/reconciler-arxiv-action@master
        with:
          arxiv_id: "2005.12660"
