name: arxiv-reproducibility
on: [push, pull_request]
env:
  ARGS: --full
  ARXIV_ID: "2005.12660"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build/Run Docker code
        run: make docker ARGS=${{ env.ARGS }}
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@master
        with:
          name: output
          path: ./ms.pdf
  build-arxiv:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Get arxiv results
        run: make arxiv ARXIV_ID=${{ env.ARXIV_ID }}
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@master
        with:
          name: output-arxiv
          path: ./ms.pdf
  compare:
    needs: [build, build-arxiv]
    runs-on: ubuntu-latest
    steps:
      - name: Download pdfs from build
        uses: actions/download-artifact@master
      - name: Compare pdf binaries
        run: diff output/ms.pdf output-arxiv/ms.pdf
