name: arxiv-reproducibility
on: [push, pull_request]
env:
  ARGS: --full
  DOCKER_WORKDIR: /usr/src/app
  ARXIV_ID: "2005.12660"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build/Run Docker code
        run: make results ARGS={{ env.ARGS }}
      - name: Run Docker latex
        run: |
          docker run --rm \
          -v $GITHUB_WORKSPACE/:/doc/ \
          thomasweise/docker-texlive-full \
          latexmk -pdf -quiet -cd /doc/ms.tex
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@master
        with:
          name: output
          path: ./ms.pdf
  build-arxiv:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Get arxiv results
        run: curl -LO https://arxiv.org/e-print/${{ env.ARXIV_ID }}
      - name: Uncompress arxiv
        run: tar -xvf ${{ env.ARXIV_ID }}
      - name: Run Docker latex
        run: docker run -v $GITHUB_WORKSPACE/:/doc/ thomasweise/docker-texlive-full latexmk -pdf -quiet -cd /doc/ms.tex
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@master
        with:
          name: output-arxiv
          path: ./ms.pdf
  compare:
    needs: [build, build-arxiv]
    runs-on: ubuntu-latest
    steps:
      - name: Download pdfs from build
        uses: actions/download-artifact@master
      - name: Compare pdf binaries
        run: diff output/ms.pdf output-arxiv/ms.pdf
