name: list
on:
  schedule:
    - cron:  '*/15 * * * *'
jobs:
  listProjects:
    runs-on: ubuntu-latest
    steps:
      - name: Run curl
        run: curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/search/code?q=pbizopoulos/reconciler-action+path:.github/workflows'
