name: list
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  listProjects:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Run curl
        run: curl 'https://api.github.com/search/code?q=pbizopoulos/reconciler-action+path:.github/workflows'
