name: reproducibility
on: [push, pull_request]
env:
  ARGS: --full
  DOCKER_WORKDIR: /usr/src/app
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build/Run Docker code
        run: |
          python3 -m pip install -U pip wheel
          python3 -m pip install -Ur requirements.txt
          python3 main.py $(ARGS)
      - name: Run Docker latex
        run: |
          docker run --rm \
          -v $GITHUB_WORKSPACE/:/doc/ \
          thomasweise/docker-texlive-full \
          latexmk -pdf -quiet -cd /doc/ms.tex
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@master
        with:
          name: output-${{ matrix.os }}
          path: ./ms.pdf
  compare:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download pdfs from build
        uses: actions/download-artifact@master
      - name: Compare pdf binaries
        run: diff output-ubuntu-16.04/ms.pdf output-ubuntu-18.04/ms.pdf
