name: reproducibility
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Certify paper reproducibility
        uses: pbizopoulos/reconciler-action@master
        with:
          root_code: main.py
          root_code_args: "--full"
