name: reproducibility
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Certify Paper
        uses: pbizopoulos/reconciler-action@master
