name: reproducible-build
on: [push, pull_request]
env:
  ARGS: --full
  ARXIV_ID: '2005.12660'
jobs:
  release:
    runs-on: ubuntu-20.04
    outputs: 
      upload_url: ${{ steps.create_release.outputs.upload_url }} 
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1
          release_name: Release v1
          draft: false
          prerelease: false
  build-arxiv:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        index: [0, 1]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: make arxiv
        run: make arxiv ARXIV_ID=${{ env.ARXIV_ID }}
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@v2
        with:
          name: arxiv-${{ matrix.os }}-${{ matrix.index }}
          path: ./ms.pdf
  build-local:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        index: [0, 1]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv
        shell: bash
      - name: make
        run: make ARGS=${{ env.ARGS }}
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@v2
        with:
          name: local-${{ matrix.os }}-${{ matrix.index }}
          path: ./ms.pdf
  build-docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        index: [0, 1]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build/Run Docker code
        run: make docker ARGS=${{ env.ARGS }}
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@v2
        with:
          name: docker-${{ matrix.os }}-${{ matrix.index }}
          path: ./ms.pdf
  compare-and-upload-release-assets:
    needs: [release, build-arxiv, build-local, build-docker]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        var: [arxiv, local, docker]
    steps:
      - name: Download pdfs from build
        uses: actions/download-artifact@v2
      - name: Compare pdf binaries
        run: diff ${{ matrix.var }}-${{ matrix.os }}-0/ms.pdf ${{ matrix.var }}-${{ matrix.os }}-1/ms.pdf
      - name: Rename pdf binaries
        run: mv ${{ matrix.var }}-${{ matrix.os }}-0/ms.pdf ${{ matrix.var }}-${{ matrix.os }}.pdf
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./${{ matrix.var }}-${{ matrix.os }}.pdf
          asset_name: ${{ matrix.var }}-${{ matrix.os }}.pdf
          asset_content_type: application/pdf
      - name: Create sha256sum asset
        run: sha256sum ${{ matrix.var }}-${{ matrix.os }}.pdf | cut -d " " -f 1 > ${{ matrix.var }}-${{ matrix.os }}.sha256
      - name: Upload sha256sum to releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./${{ matrix.var }}-${{ matrix.os }}.sha256
          asset_name: ${{ matrix.var }}-${{ matrix.os }}.sha256
          asset_content_type: application/text
