name: reproducible-build
on: [push, pull_request]
jobs:
  release:
    if: contains(github.event.head_commit.message, '{release}')
    runs-on: ubuntu-20.04
    outputs: 
      upload_url: ${{ steps.create_release.outputs.upload_url }} 
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1
          release_name: Release v1
          draft: false
          prerelease: false
  build-arxiv:
    if: contains(github.event.head_commit.message, '[')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        index: [0, 1]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: make arxiv
        run: |
          make arxiv ARXIV_ID=$(echo ${{ github.event.head_commit.message }} | awk -F'[][]' '{print $2}')
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@v2
        with:
          name: arxiv-${{ matrix.os }}-${{ matrix.index }}
          path: ./ms.pdf
  build-local:
    if: contains(github.event.head_commit.message, '{') || contains(github.event.head_commit.message, '[')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        index: [0, 1]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv
        shell: bash
      - if: contains(github.event.head_commit.message, '{full}')
        name: make
        run: make ARGS=--full
      - if: "!contains(github.event.head_commit.message, '{full}')"
        name: make
        run: make
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@v2
        with:
          name: local-${{ matrix.os }}-${{ matrix.index }}
          path: ./ms.pdf
  build-docker:
    if: contains(github.event.head_commit.message, '{') || contains(github.event.head_commit.message, '[')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        index: [0, 1]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - if: contains(github.event.head_commit.message, '{full}')
        name: Build/Run Docker code
        run: make docker ARGS=--full
      - if: "!contains(github.event.head_commit.message, '{full}')"
        name: Build/Run Docker code
        run: make docker
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@v2
        with:
          name: docker-${{ matrix.os }}-${{ matrix.index }}
          path: ./ms.pdf
  compare-release-assets:
    if: contains(github.event.head_commit.message, '{') || contains(github.event.head_commit.message, '[')
    needs: [build-arxiv, build-local, build-docker]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        var: [arxiv, local, docker]
    steps:
      - name: Download pdfs from build
        uses: actions/download-artifact@v2
      - name: Compare pdf binaries
        run: diff ${{ matrix.var }}-${{ matrix.os }}-0/ms.pdf ${{ matrix.var }}-${{ matrix.os }}-1/ms.pdf
  upload-release-assets:
    if: contains(github.event.head_commit.message, '{release}')
    needs: [release, build-arxiv, build-local, build-docker]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        var: [arxiv, local, docker]
    steps:
      - name: Download pdfs from build
        uses: actions/download-artifact@v2
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./${{ matrix.var }}-${{ matrix.os }}-0.pdf
          asset_name: ${{ matrix.var }}-${{ matrix.os }}.pdf
          asset_content_type: application/pdf
      - name: Create sha256sum asset
        run: sha256sum ${{ matrix.var }}-${{ matrix.os }}-0.pdf | cut -d " " -f 1 > ${{ matrix.var }}-${{ matrix.os }}.sha256
      - name: Upload sha256sum to releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./${{ matrix.var }}-${{ matrix.os }}.sha256
          asset_name: ${{ matrix.var }}-${{ matrix.os }}.sha256
          asset_content_type: application/text
