name: reproducible-build
on: [push, pull_request]
env:
  ARGS: --full
  ARXIV_ID: '2005.12660'
jobs:
  release:
    runs-on: ubuntu-20.04
    outputs: 
    upload_url: ${{ steps.create_release.outputs.upload_url }} 
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  build-arxiv:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: make arxiv
        run: make arxiv ARXIV_ID=${{ env.ARXIV_ID }}
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@v2
        with:
          name: arxiv
          path: ./ms.pdf
  build-local:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        index: [0, 1]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv
        shell: bash
      - name: make
        run: make ARGS=${{ env.ARGS }}
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@v2
        with:
          name: local-${{ matrix.os }}-${{ matrix.index }}
          path: ./ms.pdf
  build-docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]
        index: [0, 1]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build/Run Docker code
        run: make docker ARGS=${{ env.ARGS }}
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@v2
        with:
          name: docker-${{ matrix.os }}-${{ matrix.index }}
          path: ./ms.pdf
  build-linux-other:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['centos', 'archlinux']
        index: [0, 1]
    container: ${{ matrix.os }}
    steps:
      - name: install toolchain
        if: contains(matrix.os, 'centos')
        run: yum install -y make docker
      - name: install toolchain
        if: contains(matrix.os, 'archlinux')
        run: pacman -Syy --noconfirm make docker
      - name: Build/Run Docker code
        run: make docker ARGS=${{ env.ARGS }}
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@v2
        with:
          name: docker-${{ matrix.os }}-${{ matrix.index }}
          path: ./ms.pdf
  compare-local-ubuntu-20-04:
    needs: [release, build-local]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Download pdfs from build
        uses: actions/download-artifact@v2
      - name: Compare pdf binaries
        run: diff local-${{ matrix.os }}-0/ms.pdf local-${{ matrix.os }}-1/ms.pdf
      - name: Compare pdf binaries
        run: mv local-${{ matrix.os }}-0/ms.pdf local-${{ matrix.os }}.pdf
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./local-${{ matrix.os }}.pdf
          asset_name: local-${{ matrix.os }}.pdf
          asset_content_type: application/pdf
  compare-docker-ubuntu-20-04:
    needs: [release, build-docker]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Download pdfs from build
        uses: actions/download-artifact@v2
      - name: Compare pdf binaries
        run: diff docker-${{ matrix.os }}-0/ms.pdf docker-${{ matrix.os }}-1/ms.pdf
      - name: Compare pdf binaries
        run: mv docker-${{ matrix.os }}-0/ms.pdf docker-${{ matrix.os }}.pdf
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./docker-${{ matrix.os }}.pdf
          asset_name: docker-${{ matrix.os }}.pdf
          asset_content_type: application/pdf
  compare-docker-ubuntu-18-04:
    needs: [release, build-docker]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Download pdfs from build
        uses: actions/download-artifact@v2
      - name: Compare pdf binaries
        run: diff docker-${{ matrix.os }}-0/ms.pdf docker-${{ matrix.os }}-1/ms.pdf
      - name: Compare pdf binaries
        run: mv docker-${{ matrix.os }}-0/ms.pdf docker-${{ matrix.os }}.pdf
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./docker-${{ matrix.os }}.pdf
          asset_name: docker-${{ matrix.os }}.pdf
          asset_content_type: application/pdf
  compare-docker-ubuntu-16-04:
    needs: [release, build-docker]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu-16.04]
    steps:
      - name: Download pdfs from build
        uses: actions/download-artifact@v2
      - name: Compare pdf binaries
        run: diff docker-${{ matrix.os }}-0/ms.pdf docker-${{ matrix.os }}-1/ms.pdf
      - name: Compare pdf binaries
        run: mv docker-${{ matrix.os }}-0/ms.pdf docker-${{ matrix.os }}.pdf
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./docker-${{ matrix.os }}.pdf
          asset_name: docker-${{ matrix.os }}.pdf
          asset_content_type: application/pdf
  compare-docker-archlinux:
    needs: [release, build-linux-other]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [archlinux]
    steps:
      - name: Download pdfs from build
        uses: actions/download-artifact@v2
      - name: Compare pdf binaries
        run: diff docker-${{ matrix.os }}-0/ms.pdf docker-${{ matrix.os }}-1/ms.pdf
      - name: Compare pdf binaries
        run: mv docker-${{ matrix.os }}-0/ms.pdf docker-${{ matrix.os }}.pdf
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./docker-${{ matrix.os }}.pdf
          asset_name: docker-${{ matrix.os }}.pdf
          asset_content_type: application/pdf
  compare-docker-centos:
    needs: [release, build-linux-other]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [centos]
    steps:
      - name: Download pdfs from build
        uses: actions/download-artifact@v2
      - name: Compare pdf binaries
        run: diff docker-${{ matrix.os }}-0/ms.pdf docker-${{ matrix.os }}-1/ms.pdf
      - name: Compare pdf binaries
        run: mv docker-${{ matrix.os }}-0/ms.pdf docker-${{ matrix.os }}.pdf
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./docker-${{ matrix.os }}.pdf
          asset_name: docker-${{ matrix.os }}.pdf
          asset_content_type: application/pdf
  compare:
    needs: [build-arxiv, compare-local-ubuntu-20-04, compare-docker-ubuntu-20-04, compare-docker-ubuntu-18-04, compare-docker-ubuntu-16-04, compare-docker-archlinux, compare-docker-centos]
    runs-on: ubuntu-20.04
    steps:
      - name: Download pdfs from build
        uses: actions/download-artifact@v2
      - name: Compare pdf binaries
        run: diff --from-file arxiv/ms.pdf local-ubuntu-20.04-0/ms.pdf docker-ubuntu-20.04-0/ms.pdf docker-ubuntu-18.04-0/ms.pdf docker-ubuntu-16.04-0/ms.pdf
      - name: Create file with sha256sum name
        run: echo ::set-env name=sha256sumfilename::$(sha256sum local-ubuntu-20.04/ms.pdf | cut -d ' ' -f1)
      - name: Upload file with sha256sum name
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.sha256sumfilename }}
          path: .
