name: reproducible-build
on: [push, pull_request]
env:
  ARGS: --full
  ARXIV_ID: '2005.12660'
jobs:
  release:
    runs-on: ubuntu-20.04
    outputs: 
      upload_url: ${{ steps.create_release.outputs.upload_url }} 
    steps:
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
  build-arxiv:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        index: [0, 1]
    steps:
        uses: actions/checkout@v2
        run: make arxiv ARXIV_ID=${{ env.ARXIV_ID }}
        uses: actions/upload-artifact@v2
        with:
          name: arxiv-${{ matrix.os }}-${{ matrix.index }}
          path: ./ms.pdf
  build-local:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        index: [0, 1]
    steps:
        uses: actions/checkout@v2
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv
        shell: bash
        run: make ARGS=${{ env.ARGS }}
        uses: actions/upload-artifact@v2
        with:
          name: local-${{ matrix.os }}-${{ matrix.index }}
          path: ./ms.pdf
  build-docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        index: [0, 1]
    steps:
        uses: actions/checkout@v2
        run: make docker ARGS=${{ env.ARGS }}
        uses: actions/upload-artifact@v2
        with:
          name: docker-${{ matrix.os }}-${{ matrix.index }}
          path: ./ms.pdf
  compare-and-upload-release-assets:
    needs: [release, build-arxiv, build-local, build-docker]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        var: [arxiv, local, docker]
    steps:
        uses: actions/download-artifact@v2
        run: diff ${{ matrix.var }}-${{ matrix.os }}-0/ms.pdf ${{ matrix.var }}-${{ matrix.os }}-1/ms.pdf
        run: mv ${{ matrix.var }}-${{ matrix.os }}-0/ms.pdf ${{ matrix.var }}-${{ matrix.os }}.pdf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./${{ matrix.var }}-${{ matrix.os }}.pdf
          asset_name: ${{ matrix.var }}-${{ matrix.os }}.pdf
          asset_content_type: application/pdf
        run: sha256sum -b arxiv-ubuntu-20.04-0/ms.pdf local-ubuntu-20.04-0/ms.pdf docker-ubuntu-20.04-0/ms.pdf > sha256sum.txt
        uses: actions/upload-artifact@v2
        with:
          name: sha256sum.txt
          path: .
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./sha256sum.txt
          asset_name: sha256sum.txt
          asset_content_type: application/text
