name: reproducible-build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
env:
  ARGS: --full
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build/Run Docker code
        run: make docker ARGS=${{ env.ARGS }}
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@master
        with:
          name: output-${{ matrix.os }}
          path: ./ms.pdf
  compare:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download pdfs from build
        uses: actions/download-artifact@master
      - name: Compare pdf binaries
        run: diff output-ubuntu-16.04/ms.pdf output-ubuntu-18.04/ms.pdf
